// ข้อความบนหน้าจอทั้งหมด (spec §12 — "แยกข้อความออกจาก component")
//
// กติกาของโปรเจกต์: **ห้ามเขียนข้อความไทยลง component ตรง ๆ** ให้อ้างจากที่นี่
// วันที่จะเพิ่มภาษา จะได้เปลี่ยนเป็น dictionary ต่อภาษาโดยไม่ต้องไล่แก้ทุกไฟล์
//
// จัดกลุ่มตามหน้าจอ ไม่ใช่ตามชนิดของคำ เพื่อให้หาเจอจากชื่อหน้าที่กำลังแก้อยู่

export const COMMON = {
  save: "บันทึก",
  saveChanges: "บันทึกการเปลี่ยนแปลง",
  cancel: "ยกเลิก",
  edit: "แก้ไข",
  add: "เพิ่ม",
  remove: "ลบออก",
  close: "ปิด",
  search: "ค้นหา",
  loading: "กำลังทำงาน...",
  confirm: "ยืนยัน",
  back: "ย้อนกลับ",
  none: "—",
  optional: "(ไม่บังคับ)",
  copy: "คัดลอก",
  copied: "คัดลอกแล้ว",
  showAll: "ดูทั้งหมด",
  active: "ใช้งานอยู่",
  inactive: "ปิดใช้งาน",
  archived: "เก็บถาวร",
  locked: "ถูกล็อก",
  yes: "ใช่",
  no: "ไม่ใช่",
} as const

export const BRAND = {
  name: "e-Saraban",
  tagline: "ระบบสารบรรณอิเล็กทรอนิกส์",
  organization: "มหาวิทยาลัยเกริก",
  copyright: "© 2569 มหาวิทยาลัยเกริก · e-Saraban v1.0",
  logoAlt: "ตราสัญลักษณ์มหาวิทยาลัยเกริก",
} as const

export const NAV = {
  groupMain: null,
  groupRegistry: "สารบรรณ",
  groupAdmin: "ผู้ดูแลระบบ",

  dashboard: "ภาพรวม",
  inbox: "กล่องรับเอกสาร",
  outbox: "กล่องส่งเอกสาร",
  drafts: "ร่างของฉัน",

  registry: "ทะเบียนหนังสือ",
  registryIncoming: "ทะเบียนรับ",
  registryOutgoing: "ออกเลขหนังสือ",
  registrySent: "ทะเบียนส่ง",
  search: "ค้นหาขั้นสูง",
  reports: "รายงานทะเบียน",

  orgStructure: "โครงสร้างองค์กร",
  orgUnits: "หน่วยงาน",
  users: "ผู้ใช้งาน",
  roles: "บทบาทและสิทธิ์",
  systemSettings: "ตั้งค่าระบบ",
  numbering: "รูปแบบเลขหนังสือ",
  generalSettings: "ค่าตั้งทั่วไป",
  audit: "ตรวจสอบ Audit",
} as const

export const HEADER = {
  workingAs: "กำลังทำงานในนาม",
  switchUnit: "สลับหน่วยงาน",
  searchPlaceholder: "ค้นหาเลขที่หนังสือ, เรื่อง, ชื่อผู้ส่ง...",
  notifications: "การแจ้งเตือน",
  toggleTheme: "สลับธีมสว่าง/มืด",
  openMenu: "เปิดเมนู",
  closeMenu: "ปิดเมนู",
  editProfile: "แก้ไขโปรไฟล์",
  changePassword: "เปลี่ยนรหัสผ่าน",
  logout: "ออกจากระบบ",
  singleAffiliation: "สังกัดเดียว",
} as const

export const LOGIN = {
  heroTitle: "จัดการหนังสือราชการได้ครบในที่เดียว",
  heroSubtitle:
    "ลดขั้นตอนงานสารบรรณ ออกเลขทะเบียนอัตโนมัติ ควบคุมชั้นความลับ และตรวจสอบย้อนหลังได้ทุกการกระทำ",
  features: [
    "ควบคุมชั้นความลับ 4 ระดับ พร้อมเข้ารหัสไฟล์แนบ",
    "ออกเลขทะเบียนอัตโนมัติ แยกตามหน่วยงานและปี",
    "ตรวจสอบย้อนหลังได้ทุกการกระทำ (audit log)",
  ],
  title: "เข้าสู่ระบบ",
  subtitle: "กรอกชื่อผู้ใช้หรืออีเมลของหน่วยงานคุณ",
  username: "ชื่อผู้ใช้หรืออีเมล",
  usernamePlaceholder: "เช่น rattana.wong หรือ rattana.wong@krirk.ac.th",
  password: "รหัสผ่าน",
  passwordPlaceholder: "กรอกรหัสผ่าน",
  forgot: "ลืมรหัสผ่าน?",
  remember: "จดจำการเข้าสู่ระบบไว้ 8 ชั่วโมง",
  submit: "เข้าสู่ระบบ",
  submitting: "กำลังตรวจสอบ...",
  noAccount: "ยังไม่มีบัญชีผู้ใช้งาน?",
  registerLink: "ลงทะเบียนใช้งาน",
  contactAdmin: "หรือติดต่อผู้ดูแลระบบหน่วยงานของคุณ",
  showPassword: "แสดงรหัสผ่าน",
  hidePassword: "ซ่อนรหัสผ่าน",
} as const

export const FORGOT_PASSWORD = {
  heroTitle: "กู้คืนการเข้าถึงบัญชีของคุณ",
  heroSubtitle:
    "MVP นี้ยังไม่มีการแจ้งเตือนทางอีเมล คำขอของคุณจะถูกส่งเข้าคิวให้ผู้ดูแลระบบตรวจสอบและรีเซ็ตรหัสผ่านให้โดยตรง",
  backToLogin: "กลับไปหน้าเข้าสู่ระบบ",
  title: "ลืมรหัสผ่าน?",
  subtitle: "กรอกอีเมลที่ลงทะเบียนไว้กับบัญชี ระบบจะส่งคำขอไปยังผู้ดูแลระบบให้รีเซ็ตรหัสผ่านให้",
  email: "อีเมลของหน่วยงาน",
  emailPlaceholder: "rattana.wong@krirk.ac.th",
  submit: "ส่งคำขอรีเซ็ตรหัสผ่าน",
  submitting: "กำลังส่งคำขอ...",
  sentTitle: "ส่งคำขอเรียบร้อยแล้ว",
  sentBody:
    "ผู้ดูแลระบบจะตรวจสอบและติดต่อกลับพร้อมรหัสผ่านชั่วคราว หากเร่งด่วนสามารถติดต่อผู้ดูแลระบบของหน่วยงานได้โดยตรง",
  notice:
    "ระบบตอบผลลัพธ์เหมือนกันทุกครั้ง ไม่ว่าอีเมลนั้นจะมีบัญชีในระบบหรือไม่ เพื่อไม่ให้หน้านี้ถูกใช้ตรวจสอบว่าอีเมลใดมีบัญชีอยู่",
} as const

export const REGISTER = {
  heroTitle: "ลงทะเบียนใช้งานสำหรับหน่วยงานของคุณ",
  heroSubtitle:
    "คำขอของคุณจะถูกส่งไปยังผู้ดูแลระบบเพื่อตรวจสอบและอนุมัติสิทธิ์การใช้งานก่อนเข้าสู่ระบบได้",
  backToLogin: "กลับไปหน้าเข้าสู่ระบบ",
  title: "ลงทะเบียนผู้ใช้ใหม่",
  subtitle:
    "กรอกข้อมูลของคุณให้ครบถ้วน ระบบจะส่งคำขอไปยังผู้ดูแลระบบเพื่อตรวจสอบก่อนเปิดใช้งานบัญชี",
  firstName: "ชื่อ",
  firstNamePlaceholder: "เช่น รัตนา",
  lastName: "นามสกุล",
  lastNamePlaceholder: "เช่น วงศ์ประเสริฐ",
  email: "อีเมลของหน่วยงาน",
  emailPlaceholder: "rattana.wong@krirk.ac.th",
  emailHint: "ระบบจะสร้างชื่อผู้ใช้สำหรับเข้าสู่ระบบจากอีเมลนี้ให้อัตโนมัติ",
  orgUnit: "หน่วยงานที่สังกัด",
  orgUnitPlaceholder: "เลือกหน่วยงาน...",
  positionTitle: "ตำแหน่ง",
  positionPlaceholder: "เช่น เจ้าหน้าที่บริหารงานทั่วไป",
  password: "รหัสผ่าน",
  passwordPlaceholder: (minLength: number) => `อย่างน้อย ${minLength} ตัวอักษร`,
  confirmPassword: "ยืนยันรหัสผ่าน",
  confirmPasswordPlaceholder: "กรอกรหัสผ่านอีกครั้ง",
  passwordMismatch: "รหัสผ่านไม่ตรงกัน",
  showPassword: "แสดงรหัสผ่าน",
  hidePassword: "ซ่อนรหัสผ่าน",
  note: "หมายเหตุถึงผู้ดูแลระบบ",
  notePlaceholder: "ระบุเหตุผลหรือข้อมูลเพิ่มเติม (ถ้ามี)",
  submit: "ส่งคำขอลงทะเบียน",
  submitting: "กำลังส่งคำขอ...",
  haveAccount: "มีบัญชีอยู่แล้ว?",
  loginLink: "เข้าสู่ระบบ",
  successTitle: "ส่งคำขอลงทะเบียนแล้ว",
  successLeadPrefix: "คำขอของ",
  successLeadSuffix: "ถูกส่งไปยังผู้ดูแลระบบของ",
  // MVP ยังไม่มีการแจ้งเตือนทางอีเมล (D10) จึงไม่สัญญาว่าจะมีอีเมลแจ้งผล
  successNoticePrefix: "ผู้ดูแลระบบของหน่วยงานจะตรวจสอบคำขอและติดต่อกลับที่",
  successNoticeSuffix:
    "เมื่ออนุมัติแล้ว คุณจะเข้าสู่ระบบด้วยชื่อผู้ใช้ข้างบนกับรหัสผ่านที่ตั้งไว้ได้ทันที",
  successUsernameLabel: "ชื่อผู้ใช้สำหรับเข้าสู่ระบบ",
  successUsernameHint: "จดไว้ก่อนปิดหน้านี้ — ระบบสร้างให้จากอีเมลของคุณ",
} as const

export const CHANGE_PASSWORD = {
  title: "เปลี่ยนรหัสผ่าน",
  firstTimeTitle: "ตั้งรหัสผ่านใหม่ก่อนเริ่มใช้งาน",
  firstTimeBody:
    "บัญชีนี้ยังใช้รหัสผ่านชั่วคราวที่ผู้ดูแลระบบตั้งให้ กรุณาตั้งรหัสผ่านของคุณเองก่อนเข้าใช้งานระบบ",
  currentPassword: "รหัสผ่านปัจจุบัน",
  newPassword: "รหัสผ่านใหม่",
  confirmPassword: "ยืนยันรหัสผ่านใหม่",
  submit: "บันทึกรหัสผ่านใหม่",
  submitting: "กำลังบันทึก...",
  policyTitle: "ข้อกำหนดของรหัสผ่าน",
  policyItems: (minLength: number) => [
    `ยาวอย่างน้อย ${minLength} ตัวอักษร`,
    "มีอักขระอย่างน้อย 2 ประเภท (ตัวอักษร ตัวเลข หรือสัญลักษณ์)",
    "ต้องไม่เป็นรหัสผ่านที่พบบ่อย และไม่มีชื่อผู้ใช้อยู่ข้างใน",
  ],
} as const

export const DASHBOARD = {
  title: "ภาพรวม",
  newDocument: "สร้างหนังสือใหม่",
  statOrgUnits: "หน่วยงานที่ใช้งานอยู่",
  statUsers: "ผู้ใช้งานที่เปิดใช้งาน",
  statMyAffiliations: "สังกัดของฉัน",
  statPendingRegistrations: "คำขอสมัครรออนุมัติ",
  statPendingResets: "คำขอรีเซ็ตรหัสผ่าน",
  statAuditToday: "เหตุการณ์วันนี้",
  statDeniedToday: "การเข้าถึงที่ถูกปฏิเสธวันนี้",
  statLockedUsers: "บัญชีที่ถูกล็อกอยู่",
  recentActivity: "กิจกรรมล่าสุด",
  recentActivityEmpty: "ยังไม่มีกิจกรรมในระบบ",
  myAffiliations: "สังกัดและบทบาทของฉัน",
  primaryBadge: "สังกัดหลัก",

  // ── สถิติฝั่งเอกสาร (P4) ──────────────────────────────────────────
  documentSection: "งานหนังสือ",
  identitySection: "ผู้ใช้และหน่วยงาน",
  statPendingNumber: "รอออกเลขทะเบียน",
  statAwaitingAck: "รอฉันรับทราบ",
  statMyDrafts: "ร่างของฉัน",
  statMyReturned: "ถูกตีกลับให้แก้",
  monthSection: "หนังสือที่ออกเลขเดือนนี้",
  monthInternal: "บันทึกข้อความภายใน",
  monthOutgoing: "หนังสือส่งภายนอก",
  monthIncoming: "หนังสือรับ",
  awaitingAckTitle: "รอฉันรับทราบ",
  awaitingAckEmpty: "ไม่มีหนังสือค้างรับทราบ",
  awaitingAckDue: (date: string) => `กำหนดภายใน ${date}`,
  noDocNoYet: "ยังไม่มีเลข",
} as const

export const ORG_UNITS = {
  title: "โครงสร้างหน่วยงาน",
  description: "โครงสร้างลำดับชั้นไม่จำกัดระดับ · ย้ายหน่วยงานได้โดยเลือกหน่วยงานแม่ใหม่",
  addUnit: "เพิ่มหน่วยงาน",
  treeTitle: "ผังหน่วยงาน",
  detailTitle: "รายละเอียดหน่วยงาน",
  selectPrompt: "เลือกหน่วยงานจากผังทางซ้ายเพื่อดูรายละเอียด",
  nameTh: "ชื่อหน่วยงาน (เต็ม)",
  shortName: "ชื่อย่อ",
  code: "รหัสหนังสือ",
  type: "ประเภทหน่วยงาน",
  parent: "หน่วยงานแม่",
  rootOption: "— ไม่มี (เป็นหน่วยงานสูงสุด) —",
  head: "หัวหน้าหน่วยงาน",
  headNone: "ยังไม่ได้กำหนด",
  sortOrder: "ลำดับการแสดง",
  stats: "สถิติ",
  memberCount: "ผู้ใช้ในหน่วยงาน",
  childCount: "หน่วยงานลูก",
  archive: "เก็บถาวร",
  restore: "นำกลับมาใช้",
  move: "ย้ายหน่วยงาน",
  moveTo: "ย้ายไปอยู่ใต้",
  archiveNotice:
    "หน่วยงานที่มีเอกสารผูกอยู่ลบไม่ได้ — ใช้การเก็บถาวรแทนเพื่อรักษาทะเบียนย้อนหลัง (spec §5.1)",
  showArchived: "แสดงหน่วยงานที่เก็บถาวรแล้ว",
  createTitle: "เพิ่มหน่วยงานใหม่",
  codeHint: "รหัสงานสารบรรณ 6 หลัก เช่น 510200 — เป็นส่วนหน้าของเลขทะเบียน",
  canIssueNumber: "ออกเลขหนังสือในนามหน่วยงานนี้ได้",
  canIssueNumberHint:
    "หน่วยระดับ “งาน” และหลักสูตรออกเลขไม่ได้ตามกติกาที่ตกลงไว้ (spec D15) — ปิดไว้แล้วรหัสหน่วยงานนี้จะไม่ถูกใช้เป็นเลขทะเบียน",
  cannotIssue: "ออกเลขไม่ได้",

  registrarTitle: "นายทะเบียนหนังสือลับ",
  registrarDescription:
    "ผู้ที่ออกเลขทะเบียนให้เอกสารชั้นความลับของหน่วยงานนี้ได้ · เห็นชื่อเรื่องในทะเบียน แต่เปิดไฟล์แนบไม่ได้",
  registrarEmpty: "ยังไม่ได้ตั้งนายทะเบียน",
  registrarEmptyWarning:
    "หน่วยงานนี้ยังส่งเอกสารชั้นความลับเข้าคิวออกเลขไม่ได้ — ระบบจะปฏิเสธตั้งแต่ตอนกดส่ง จนกว่าจะตั้งนายทะเบียนอย่างน้อยหนึ่งคน",
  registrarAdd: "เพิ่มนายทะเบียน",
  registrarAddPlaceholder: "เลือกผู้ใช้...",
  registrarRemove: "ถอนออกจากตำแหน่ง",
  registrarClearanceHint: (level: number) => `ชั้นความลับ ${level}`,
  registrarClearanceWarning: "ชั้นความลับ 0 เป็นนายทะเบียนหนังสือลับไม่ได้",
  registrarOnlyIssuingUnit:
    "หน่วยงานนี้ออกเลขหนังสือไม่ได้ จึงไม่ต้องมีนายทะเบียนหนังสือลับ — เอกสารของหน่วยนี้ออกเลขในนามหน่วยงานแม่",
  registrarAssignedBy: (name: string, at: string) => `ตั้งโดย ${name} · ${at}`,
  searchPlaceholder: "ค้นหาชื่อหรือรหัสหน่วยงาน...",
  searchEmpty: "ไม่พบหน่วยงานที่ตรงกับคำค้น",
  matchCount: (found: number, total: number) =>
    `พบ ${found.toLocaleString("th-TH")} หน่วยงาน จากทั้งหมด ${total.toLocaleString("th-TH")}`,
  expandAll: "กางทั้งหมด",
  collapseAll: "พับทั้งหมด",
  unitCount: (total: number, issuing: number) =>
    `${total.toLocaleString("th-TH")} หน่วยงาน · ออกเลขได้ ${issuing.toLocaleString("th-TH")}`,
} as const

export const DOCUMENTS = {
  // ── หน้ารายการ ──────────────────────────────────────────────
  draftsTitle: "ร่างของฉัน",
  draftsDescription: "หนังสือที่คุณร่างไว้และที่ถูกตีกลับให้แก้ไข",
  inboxTitle: "กล่องรับเอกสาร",
  inboxDescription: "หนังสือที่ส่งถึงคุณหรือหน่วยงานของคุณ",
  outboxTitle: "กล่องส่งเอกสาร",
  outboxDescription: "หนังสือที่หน่วยงานของคุณออกเลขและส่งออกแล้ว",
  queueTitle: "ออกเลขหนังสือ",
  queueDescription: "คิวหนังสือที่รอสารบรรณออกเลขทะเบียน",
  registrySentTitle: "ทะเบียนส่ง",
  registrySentDescription: "หนังสือที่ออกเลขไปแล้วทั้งหมด รวมฉบับที่ยกเลิก",
  registryIncomingTitle: "ทะเบียนรับ",
  registryIncomingDescription: "หนังสือรับที่ลงทะเบียนไว้",

  create: "สร้างหนังสือใหม่",
  registerIncoming: "ลงทะเบียนหนังสือรับ",
  searchPlaceholder: "ค้นหาเลขที่หนังสือ หรือชื่อเรื่อง...",
  search: "ค้นหา",
  clearFilter: "ล้างตัวกรอง",
  filterAll: "ทั้งหมด",
  resultCount: (total: number) => `พบ ${total.toLocaleString("th-TH")} รายการ`,
  pageInfo: (from: number, to: number, total: number) =>
    `แสดง ${from.toLocaleString("th-TH")}–${to.toLocaleString("th-TH")} จาก ${total.toLocaleString("th-TH")} รายการ`,
  prev: "ก่อนหน้า",
  next: "ถัดไป",

  // ── คอลัมน์ ─────────────────────────────────────────────────
  colSubject: "เรื่อง / เลขที่หนังสือ",
  colType: "ประเภท",
  colStatus: "สถานะ",
  colUpdated: "แก้ไขล่าสุด",
  colReturnNote: "หมายเหตุการตีกลับ",
  colSender: "ผู้ส่ง",
  colRecipient: "ผู้รับ",
  colDate: "วันที่",
  colSentDate: "วันที่ส่ง",
  colConfidentiality: "ชั้นความลับ",
  colOwnerUnit: "หน่วยงานเจ้าของเรื่อง",
  colWaiting: "รอมาแล้ว",
  colAction: "จัดการ",

  noDocNo: "ยังไม่ออกเลข",
  attachmentCount: (count: number) => `${count} ไฟล์`,
  recipientCount: (count: number) => `ผู้รับ ${count} ราย`,
  external: "ภายนอก",

  emptyDrafts: "ยังไม่มีร่างหนังสือ — กดปุ่มสร้างหนังสือใหม่เพื่อเริ่ม",
  emptyInbox: "ยังไม่มีหนังสือส่งถึงคุณ",
  emptyOutbox: "หน่วยงานนี้ยังไม่มีหนังสือที่ออกเลขแล้ว",
  emptyQueue: "ไม่มีหนังสือรอออกเลข",
  emptyRegistry: "ยังไม่มีหนังสือในทะเบียน",
  emptySearch: "ไม่พบหนังสือที่ตรงกับเงื่อนไข",

  // ── ฟอร์มสร้าง/แก้ไข ────────────────────────────────────────
  createDescription: "ร่างหนังสือแล้วส่งให้สารบรรณออกเลขทะเบียน",
  formSection: "ข้อมูลหนังสือ",
  formOwner: (unitName: string) => `เจ้าของเรื่อง: ${unitName}`,
  fieldType: "ประเภทหนังสือ",
  fieldSubject: "ชื่อเรื่อง",
  fieldSummary: "สาระสำคัญโดยย่อ",
  fieldExternalRecipient: "หน่วยงานผู้รับ (ภายนอก)",
  fieldExternalSender: "หน่วยงานผู้ส่ง",
  fieldDocDate: "วันที่ของหนังสือ",
  fieldReceivedDate: "วันที่รับหนังสือ",
  fieldDueDate: "กำหนดตอบกลับ",
  fieldRefDocNo: "อ้างถึงหนังสือเลขที่",
  fieldConfidentiality: "ชั้นความลับ",
  fieldUrgency: "ความเร่งด่วน",
  sectionLevels: "ชั้นความลับและความเร่งด่วน",
  sectionRecipients: "ผู้รับหนังสือ (ภายใน)",
  sectionRecipientsHint: "เลือกไว้ก่อนได้ หรือค่อยเวียนภายหลัง",
  fieldRecipientUnits: "หน่วยงานผู้รับ",
  unitSearchPlaceholder: "พิมพ์ชื่อหรือรหัสหน่วยงานเพื่อกรอง...",
  unitSearchEmpty: "ไม่พบหน่วยงานที่ตรงกับคำค้น",
  unitSelectedCount: (count: number) => `เลือกไว้ ${count.toLocaleString("th-TH")} หน่วยงาน`,
  unitSelectedNone: "ยังไม่ได้เลือกหน่วยงานผู้รับ",
  attachAfterSaveHint:
    "ไฟล์แนบเพิ่มได้หลังบันทึกร่างแล้ว — ระบบต้องมีเลขอ้างอิงของเอกสารก่อนจึงจะผูกไฟล์ได้",
  saveDraft: "บันทึกร่าง",
  registerIncomingDescription:
    "บันทึกหนังสือที่ได้รับจากหน่วยงานภายนอก แล้วออกเลขรับในขั้นตอนเดียว",
  incomingNumberHint:
    "กดลงทะเบียนแล้วระบบจะออกเลขรับให้ทันที — เลขที่ออกแล้วแก้ย้อนหลังไม่ได้ (spec §6.3)",
  noIncomingType: "ยังไม่มีประเภทหนังสือรับในระบบ",
  editTitle: "แก้ไขร่างหนังสือ",
  editDescription: "แก้ไขได้เฉพาะร่างและฉบับที่ถูกตีกลับ — ออกเลขแล้วแก้ไม่ได้",
  editHint: "บันทึกแล้วระบบจะเก็บไว้ในประวัติการดำเนินการว่ามีการแก้ไข",
  editTypeHint: "เปลี่ยนได้เฉพาะประเภทที่อยู่ในทิศทางเดียวกันกับฉบับนี้",
  editNotAllowed: "แก้ไขเอกสารฉบับนี้ไม่ได้",
  editNotAllowedHint: "แก้ไขได้เฉพาะสถานะร่างและถูกตีกลับเท่านั้น (spec §6.4)",
  noDocumentType: "ยังไม่มีประเภทหนังสือในระบบ",
  noDocumentTypeHint: "ผู้ดูแลระบบต้องเพิ่มประเภทหนังสือก่อนจึงจะสร้างหนังสือได้",

  // ── หน้ารายละเอียด ──────────────────────────────────────────
  detailTimeline: "ประวัติการดำเนินการ",
  detailAttachments: "ไฟล์แนบ",
  detailRecipients: "ผู้รับหนังสือ",
  detailInfo: "รายละเอียด",
  detailActions: "ดำเนินการ",
  uploadFile: "แนบไฟล์",
  uploadHint: (maxMb: number) => `รองรับ PDF · Word · Excel · รูปภาพ ขนาดไม่เกิน ${maxMb} MB`,
  download: "เปิดไฟล์",
  viewOnly: "เปิดดูอย่างเดียว",
  /** §8.3 — ต้องบอกผู้ใช้ตรง ๆ ว่าไฟล์ที่เปิดมีชื่อตัวเองติดอยู่ทุกหน้า */
  viewOnlyHint:
    "เอกสารชั้นความลับ · เปิดดูได้อย่างเดียว บันทึกลงเครื่องไม่ได้ · ไฟล์ PDF ที่เปิดจะมีลายน้ำชื่อผู้เปิด วันเวลา และหมายเลข IP ทับทุกหน้า",
  removeFile: "ลบไฟล์",
  noAttachment: "ยังไม่มีไฟล์แนบ",
  noRecipient: "ยังไม่ได้เวียนถึงใคร",
  versionLabel: (version: number) => `เวอร์ชัน ${version}`,
  noteLabel: "หมายเหตุ",
  noteRequired: "เหตุผลที่ตีกลับ",
  confirmCancel: "ยกเลิกเอกสารฉบับนี้",
  cancelWarning:
    "เลขทะเบียนที่ออกไปแล้วจะถูกจองไว้ ไม่นำกลับมาใช้ซ้ำ และเอกสารจะยังปรากฏในทะเบียนพร้อมหมายเหตุยกเลิก",

  detailTitle: "รายละเอียดหนังสือ",
  detailForbidden: "เข้าถึงเอกสารฉบับนี้ไม่ได้",
  detailSummary: "สาระสำคัญโดยย่อ",
  noSummary: "ไม่ได้กรอกสาระสำคัญไว้",
  fieldDocNo: "เลขที่หนังสือ",
  fieldOwnerUnit: "หน่วยงานเจ้าของเรื่อง",
  fieldCreatedBy: "ผู้จัดทำ",
  fieldCreatedAt: "สร้างเมื่อ",
  fieldUpdatedAt: "แก้ไขล่าสุด",
  timelineEmpty: "ยังไม่มีประวัติการดำเนินการ",
  timelineStatus: (from: string, to: string) => `${from} → ${to}`,
  actorSystem: "ระบบ",
  attachmentMeta: (size: string, uploader: string) => `${size} · ${uploader}`,
  actionNote: "หมายเหตุ",
  actionNoteHint: "ข้อความนี้จะถูกบันทึกไว้ในประวัติการดำเนินการ",
  actionRecipients: "หน่วยงานผู้รับ",
  actionConfirm: "ยืนยันการดำเนินการ",
  actionEmpty: "สถานะปัจจุบันไม่มีรายการที่คุณดำเนินการต่อได้",
  attachmentLocked: "สถานะนี้แนบไฟล์เพิ่มไม่ได้แล้ว",

  // ── ปุ่มของ transition (ตรงกับตาราง state machine) ──────────
  actionSubmit: "ส่งให้สารบรรณออกเลข",
  actionIssueNumber: "ออกเลขทะเบียน",
  actionReturn: "ตีกลับให้แก้ไข",
  actionCirculate: "เวียนหนังสือ",
  actionForward: "ส่งต่อหน่วยงาน",
  actionAcknowledge: "รับทราบ",
  actionMarkSent: "บันทึกว่าส่งออกแล้ว",
  actionClose: "ปิดเรื่อง",
  actionCancel: "ยกเลิกเอกสาร",

  // ── คิวออกเลข ───────────────────────────────────────────────
  selectAll: "เลือกทั้งหมด",
  bulkIssue: (count: number) => `ออกเลขที่เลือก (${count})`,
  bulkIssueAll: "ออกเลขที่เลือก",
  selectedCount: (count: number) => `เลือกไว้ ${count.toLocaleString("th-TH")} ฉบับ`,
  selectNone: "ยังไม่ได้เลือกฉบับใด",
  queueOrderHint: "เรียงตามความเร่งด่วนก่อน แล้วจึงตามลำดับเวลาที่ส่งเข้ามา — ใครส่งก่อนได้เลขก่อน",
  queueIrreversible: "เลขที่ออกไปแล้วแก้ย้อนหลังไม่ได้ และจะไม่ถูกนำกลับมาใช้ซ้ำแม้ยกเลิกภายหลัง",
} as const

/** สิทธิ์เฉพาะรายบนเอกสารหนึ่งฉบับ (spec §9.1) */
export const ACL = {
  title: "สิทธิ์เฉพาะราย",
  description: "ผู้ที่ได้รับสิทธิ์เข้าถึงเอกสารฉบับนี้เป็นการเฉพาะ นอกเหนือจากขอบเขตปกติ",
  empty: "ยังไม่มีการให้สิทธิ์เฉพาะราย",
  ownerTag: "เจ้าของเรื่อง",
  automaticTag: "ระบบออกให้",
  denyPrefix: "ห้าม",
  grantedBy: (name: string, at: string) => `ให้โดย ${name} · ${at}`,
  expiresOn: (date: string) => `หมดอายุ ${date}`,
  reasonLabel: "เหตุผล",
  reasonHint: "บันทึกลง Audit Log — ผู้ตรวจสอบจะเห็นว่าให้สิทธิ์นี้เพราะอะไร",
  revoke: "ถอนสิทธิ์",
  grant: "ให้สิทธิ์",
  cancel: "ยกเลิก",
  searchLabel: "ค้นหาผู้ที่จะให้สิทธิ์",
  searchPlaceholder: "ชื่อ นามสกุล หรือชื่อผู้ใช้",
  searchButton: "ค้นหา",
  noOrgUnit: "ไม่มีสังกัดหลัก",
  clearanceOf: (level: number) => `ชั้นความลับ ${level}`,
  clearanceTooLow: (level: number) => `ชั้นไม่ถึงเอกสารระดับ ${level}`,
  granteeSelected: (name: string) => `กำลังให้สิทธิ์แก่ ${name}`,
  permissionLabel: "ระดับสิทธิ์",
  effectLabel: "ผลของสิทธิ์",
  expiresLabel: "วันหมดอายุ",
  expiresHint: "เว้นว่างไว้ = ไม่มีวันหมดอายุ",
  permissionOptions: {
    VIEW: "เปิดอ่านเอกสาร",
    DOWNLOAD: "เปิดอ่าน + เปิดไฟล์แนบ",
    EDIT: "แก้ไข + แนบไฟล์",
    MANAGE: "ดูแลได้ทุกอย่าง รวมถึงให้สิทธิ์ต่อ",
  },
  permissionShort: {
    VIEW: "อ่าน",
    DOWNLOAD: "อ่าน+ไฟล์",
    EDIT: "แก้ไข",
    MANAGE: "ดูแลทั้งหมด",
    REGISTER: "นายทะเบียนลับ",
  },
  /** REGISTER ไม่อยู่ในตัวเลือกของฟอร์มให้สิทธิ์ — ระบบออกให้จากตำแหน่งเท่านั้น */
  registrarTag: "นายทะเบียนหนังสือลับ",
  effectOptions: {
    ALLOW: "อนุญาต",
    DENY: "ห้าม (ชนะทุกสิทธิ์ที่มีอยู่)",
  },
} as const

/** หน้าค้นหาขั้นสูง (spec §10.1) */
export const SEARCH = {
  title: "ค้นหาขั้นสูง",
  description: "ค้นทั้งชื่อเรื่อง เลขที่หนังสือ สาระสำคัญ และหนังสือที่อ้างถึง",
  keyword: "คำค้น",
  keywordPlaceholder: "ชื่อเรื่อง · เลขที่หนังสือ · หน่วยงานภายนอก",
  keywordHint: "ค้นคำกลางประโยคได้ ไม่ต้องพิมพ์ให้ตรงตั้งแต่ต้นคำ",
  direction: "ทิศทาง",
  status: "สถานะ",
  documentType: "ประเภทหนังสือ",
  ownerUnit: "หน่วยงานเจ้าของเรื่อง",
  ownerUnitHint: "รวมหน่วยงานลูกในสายงานเดียวกันให้อัตโนมัติ",
  confidentiality: "ชั้นความลับ",
  urgency: "ความเร่งด่วน",
  dateField: "ช่วงวันที่ของ",
  dateFieldOptions: {
    docDate: "วันที่ของหนังสือ",
    receivedDate: "วันที่รับ",
    createdAt: "วันที่บันทึกเข้าระบบ",
  },
  from: "ตั้งแต่",
  to: "ถึง",
  hasAttachment: "เฉพาะที่มีไฟล์แนบ",
  sort: "เรียงตาม",
  sortOptions: {
    latest: "ใหม่ไปเก่า",
    oldest: "เก่าไปใหม่",
    docNo: "เลขที่หนังสือ",
  },
  anyOption: "ทั้งหมด",
  submit: "ค้นหา",
  reset: "ล้างเงื่อนไข",
  resultCount: (total: number) => `พบ ${total.toLocaleString("th-TH")} ฉบับ`,
  /** ยังไม่ได้ใส่เงื่อนไข — ต่างจาก "ค้นแล้วไม่เจอ" */
  idle: "ใส่คำค้นหรือเลือกตัวกรองอย่างน้อยหนึ่งอย่าง แล้วกดค้นหา",
  notFound: "ไม่พบเอกสารที่ตรงกับเงื่อนไข",
  scopeNote: "ผลการค้นหาจำกัดอยู่ในขอบเขตที่สิทธิ์ของคุณมองเห็นได้เท่านั้น",
} as const

export const USERS = {
  title: "ผู้ใช้งาน",
  description: "จัดการบัญชี สังกัดหลายหน่วยงาน บทบาท และชั้นความลับที่เข้าถึงได้",
  addUser: "เพิ่มผู้ใช้งาน",
  searchPlaceholder: "ค้นหาชื่อ, ชื่อผู้ใช้, อีเมล...",
  listTitle: "รายชื่อผู้ใช้",
  detailTitle: "รายละเอียดผู้ใช้",
  selectPrompt: "เลือกผู้ใช้จากรายการทางซ้ายเพื่อดูรายละเอียด",
  emptyList: "ไม่พบผู้ใช้ที่ตรงกับเงื่อนไข",
  affiliations: "สังกัด & บทบาท",
  addAffiliation: "เพิ่มสังกัด",
  removeAffiliation: "ถอดสังกัด",
  primary: "สังกัดหลัก",
  clearance: "ชั้นความลับที่เข้าถึงได้",
  resetPassword: "รีเซ็ตรหัสผ่าน",
  suspend: "ระงับบัญชี",
  activate: "เปิดใช้งาน",
  lastLogin: "เข้าใช้งานล่าสุด",
  neverLoggedIn: "ยังไม่เคยเข้าใช้งาน",
  mustChangePassword: "ต้องเปลี่ยนรหัสผ่าน",
  pendingReset: "มีคำขอรีเซ็ตรหัสผ่าน",
  showInactive: "แสดงบัญชีที่ถูกระงับ",
  temporaryPasswordTitle: "รหัสผ่านชั่วคราว — แสดงเพียงครั้งเดียว",
  temporaryPasswordBody:
    "MVP ยังไม่มีการแจ้งเตือนทางอีเมล (D10) กรุณาคัดลอกรหัสผ่านนี้แล้วแจ้งผู้ใช้ด้วยช่องทางที่ปลอดภัย ระบบจะบังคับให้เปลี่ยนทันทีที่เข้าสู่ระบบครั้งแรก",
  createTitle: "เพิ่มผู้ใช้งานใหม่",
  role: "บทบาทในหน่วยงานนี้",
  registrationQueue: "คำขอสมัครใช้งาน",
  registrationEmpty: "ไม่มีคำขอรออนุมัติ",
  approve: "อนุมัติ",
  reject: "ปฏิเสธ",
  rejectReason: "เหตุผลที่ปฏิเสธ",
  resetQueue: "คำขอรีเซ็ตรหัสผ่าน",
  resetQueueEmpty: "ไม่มีคำขอรีเซ็ตรหัสผ่าน",
  requestedAt: "ส่งคำขอเมื่อ",
} as const

export const ROLES = {
  title: "บทบาทและสิทธิ์",
  description: "Role ผูกกับคู่ (ผู้ใช้, หน่วยงาน) — คนหนึ่งมีหลายบทบาทในหลายหน่วยงานพร้อมกันได้",
  roleList: "บทบาททั้งหมด",
  matrixTitle: "สิทธิ์ของบทบาท",
  scopeLegend: "ขอบเขต:",
  userCount: (n: number) => `${n} การมอบหมาย`,
  systemRole: "บทบาทของระบบ",
  save: "บันทึกสิทธิ์",
  adminNotice:
    "ผู้ดูแลระบบไม่ได้รับสิทธิ์อ่านเอกสารโดยอัตโนมัติ เพื่อป้องกันการสอดส่องเอกสาร หากจำเป็นต้องใช้กลไก break-glass ซึ่งบันทึก audit ระดับ CRITICAL (spec §4.2)",
  changeWarning:
    "การเปลี่ยนสิทธิ์ของบทบาทมีผลกับผู้ใช้ทุกคนที่ถือบทบาทนี้ทันที และถูกบันทึก audit ระดับ CRITICAL",
} as const

export const AUDIT = {
  title: "ตรวจสอบ Audit Log",
  description: "บันทึกทุกการกระทำแบบ Append-only · เชื่อมโยงด้วย Hash Chain",
  verifyChain: "ตรวจสอบความสมบูรณ์ของ Hash Chain",
  verifying: "กำลังตรวจสอบ...",
  exportCsv: "Export CSV",
  colTime: "เวลา",
  colActor: "ผู้กระทำ",
  colAction: "การกระทำ",
  colEntity: "รายการอ้างอิง",
  colResult: "ผลลัพธ์",
  colIp: "IP Address",
  filterAll: "ทั้งหมด",
  filterDenied: "ถูกปฏิเสธ",
  filterCritical: "ระดับวิกฤต",
  filterLogin: "การเข้าสู่ระบบ",
  filterAdmin: "งานผู้ดูแลระบบ",
  empty: "ไม่พบรายการที่ตรงกับเงื่อนไข",
  appendOnlyNotice:
    "ตารางนี้แก้ไขและลบไม่ได้ทั้งจากโค้ดและจากฐานข้อมูล (บังคับด้วย trigger ระดับ PostgreSQL)",
  system: "ระบบ",
  page: "หน้า",
  of: "จาก",
  previous: "ก่อนหน้า",
  next: "ถัดไป",
  total: (n: number) => `ทั้งหมด ${n.toLocaleString("th-TH")} รายการ`,
} as const

export const NUMBERING = {
  title: "รูปแบบเลขหนังสือ",
  description: "ตั้งรูปแบบเลขทะเบียนตามประเภทหนังสือ และของทะเบียนรายหน่วยงาน (spec §7.1)",

  inheritTitle: "ลำดับการตกทอดของรูปแบบ",
  inheritBody:
    "ทะเบียนของหน่วยงาน → ประเภทหนังสือ → ค่าปริยายของระบบ · เว้นว่างไว้แปลว่าใช้ค่าจากชั้นถัดไป",
  irreversible:
    "⚠️ เปลี่ยนแล้วมีผลกับเอกสารที่ออกเลข *หลังจากนี้* เท่านั้น — เลขที่ออกไปแล้วแก้ย้อนหลังไม่ได้ (spec §6.4)",

  yearModeLabel: "ปีที่ใช้รีเซ็ตเลขทะเบียน",
  yearModeCalendar: "ปีปฏิทิน (1 ม.ค. – 31 ธ.ค.)",
  yearModeFiscal: "ปีงบประมาณ (1 ต.ค. – 30 ก.ย.)",
  currentYear: "ปีทะเบียนที่ใช้อยู่",
  changeAtSettings: "เปลี่ยนได้ที่หน้าตั้งค่าระบบ",
  defaultPattern: "ค่าปริยายของระบบ",

  tokensTitle: "Token ที่ใช้ได้",
  typesTitle: "รูปแบบตามประเภทหนังสือ",
  typesDescription: "ว่างไว้ = ใช้ค่าปริยายของระบบ",
  sequencesTitle: "ทะเบียนรายหน่วยงานของปีนี้",
  sequencesDescription: "แถวจะเกิดขึ้นเองเมื่อหน่วยงานนั้นออกเลขฉบับแรกของปี",
  sequencesEmpty: "ยังไม่มีหน่วยงานใดออกเลขในปีนี้",

  colType: "ประเภทหนังสือ",
  colUnit: "หน่วยงาน",
  colDirection: "ทิศทาง",
  colBook: "เล่มทะเบียน",
  colLastValue: "เลขล่าสุด",
  colPattern: "รูปแบบ",
  colPreview: "ตัวอย่าง",

  usingDefault: "ใช้ค่าที่ตกทอดมา",
  inheritFromType: "ตามประเภทหนังสือ",
  invalidPattern: "รูปแบบยังใช้ไม่ได้",
  inactiveType: "ปิดใช้งานอยู่",
} as const

export const SETTINGS = {
  title: "ตั้งค่าระบบ",
  description: "ค่าที่มีผลกับทั้งระบบ — เปลี่ยนแล้วบันทึก audit ทุกครั้ง",
  numberingTitle: "เลขทะเบียน",
  yearMode: "ปีที่ใช้รีเซ็ตเลขทะเบียน",
  yearModeHint:
    "⚠️ เปลี่ยนภายหลังทำให้เลขทะเบียนไม่ต่อเนื่อง — ต้องยืนยันกับสารบรรณกลางก่อนเปลี่ยน (spec §7.2)",
  languageTitle: "ภาษาที่ใช้งาน",
  languageValue: "ไทย",
  languageHint: "MVP รองรับภาษาไทยอย่างเดียว (spec §12)",
  fileTitle: "ไฟล์แนบ",
  maxSize: "ขนาดไฟล์สูงสุดต่อไฟล์",
  maxSizeUnit: "MB",
  maxSizeHint: "ตรวจ magic-number ไม่เชื่อนามสกุลไฟล์ (spec §8.4)",
  allowedTypes: "ประเภทไฟล์ที่อนุญาต",
  passwordTitle: "นโยบายรหัสผ่าน",
  minLength: "ความยาวขั้นต่ำ (Argon2id)",
  minLengthUnit: "ตัวอักษร",
  mustChange: "บังคับเปลี่ยนรหัสผ่านครั้งแรก",
  mustChangeHint: "สำหรับบัญชีที่สร้างใหม่โดยผู้ดูแลระบบ",
  checkCommon: "ตรวจสอบกับ Common Password List",
  checkCommonHint: "ปฏิเสธรหัสผ่านที่พบบ่อย",
  sessionTitle: "Session & Lockout",
  idleTimeout: "Idle timeout",
  idleUnit: "นาที",
  absoluteTimeout: "Absolute timeout",
  absoluteUnit: "ชั่วโมง",
  lockoutThreshold: "จำนวนครั้งที่ผิดก่อนล็อก",
  lockoutThresholdUnit: "ครั้ง",
  lockoutBase: "ระยะเวลาล็อกตั้งต้น",
  lockoutBaseUnit: "นาที",
  lockoutHint:
    "ล็อกแบบ exponential backoff — ผิดครบเกณฑ์รอบถัดไปจะถูกล็อกนานขึ้นเป็นสองเท่า พร้อม rate limit ต่อ IP",
} as const

export const COMING_SOON = {
  badge: "อยู่ระหว่างพัฒนา",
  title: "ฟีเจอร์นี้จะมาในเฟสถัดไป",
  body: (phase: string) =>
    `หน้านี้เป็นส่วนหนึ่งของ ${phase} ตามแผนใน spec §13 — เฟสปัจจุบันคือ P1 (Identity & Org) ซึ่งครอบคลุมการยืนยันตัวตน โครงสร้างหน่วยงาน ผู้ใช้ บทบาท และ audit`,
  backToDashboard: "กลับไปหน้าภาพรวม",
} as const
